CC        := clang
DEBUGGER  := lldb
BUILD_DIR ?= build
TARGET    := $(BUILD_DIR)/ucp
SRCS      := src/main.c

TOOLCHAIN_DIR := build-toolchain
SLANG_REPO    := https://github.com/shader-slang/slang.git
SLANG_SRC     := $(TOOLCHAIN_DIR)/slang
SLANG_LOCAL   := $(TOOLCHAIN_DIR)/bin/slangc

ifeq ($(shell test -f $(SLANG_LOCAL) && echo "exists"), exists)
	SLANGC := $(SLANG_LOCAL)
else
	SLANGC := slangc
endif

CFLAGS_COMMON := -pipe -Wall -Werror -I./src -I./lib
LDFLAGS_BASE  := -lglfw -lvulkan -lm

CFLAGS_RELEASE := $(CFLAGS_COMMON) -O2 -march=native -mtune=native -flto -DNDEBUG
LDFLAGS_RELEASE := $(LDFLAGS_BASE)

CFLAGS_DEBUG := $(CFLAGS_COMMON) -O0 -g3 -DDEBUG -fsanitize=address,undefined -fno-omit-frame-pointer
LDFLAGS_DEBUG := $(LDFLAGS_BASE) -fsanitize=address,undefined

CFLAGS := $(CFLAGS_RELEASE)
LDFLAGS := $(LDFLAGS_RELEASE)

YELLOW := \033[33m
GREEN  := \033[32m
RED    := \033[31m
RESET  := \033[0m

REAL_USER := $(shell if [ -n "$$SUDO_USER" ]; then echo $$SUDO_USER; elif [ -n "$$DOAS_USER" ]; then echo $$DOAS_USER; else logname 2>/dev/null || echo $$USER; fi)
REAL_UID  := $(shell id -u $(REAL_USER) 2>/dev/null || id -u)
REAL_GID  := $(shell id -g $(REAL_USER) 2>/dev/null || id -g)

all: clean compile

run: clean compile
	@echo "$(GREEN)Running $(TARGET):$(RESET)"
	@./$(TARGET)

release: CFLAGS := $(CFLAGS_RELEASE)
release: LDFLAGS := $(LDFLAGS_RELEASE)
release: clean compile

debug: CFLAGS := $(CFLAGS_DEBUG)
debug: LDFLAGS := $(LDFLAGS_DEBUG)
debug: clean compile
	@echo "$(GREEN)Running in DEBUG mode with Sanitizers:$(RESET)"
	@./$(TARGET)

compile: $(TARGET)

$(TARGET): $(SRCS) src/shaders/shaderdump.h
	@mkdir -p $(BUILD_DIR)
	@echo "$(GREEN)Compiling $(TARGET):$(RESET)"
	$(CC) $(CFLAGS) -o $@ $(SRCS) $(LDFLAGS)


src/shaders/shaderdump.h: src/shaders/shaders.slang
	@mkdir -p $(BUILD_DIR)
	@if [ ! -f $(SLANGC) ] && ! command -v $(SLANGC) > /dev/null 2>&1; then \
		echo "$(RED)Error: slangc not found at $(SLANGC). Run 'make install-toolchain'$(RESET)"; \
		exit 1; \
	fi
	@echo "$(GREEN)Compiling shaders with $(SLANGC)...$(RESET)"
	@$(SLANGC) src/shaders/shaders.slang -target spirv -stage vertex -entry vertexMain -o /tmp/vert.spv
	@$(SLANGC) src/shaders/shaders.slang -target spirv -stage fragment -entry fragmentMain -o /tmp/frag.spv
	@echo "// Auto-generated by Make shader hex-dump" > $@
	@echo "#ifndef SHADERDUMP_H" >> $@
	@echo "#define SHADERDUMP_H" >> $@
	@echo "#include <stdint.h>" >> $@
	@echo "#include <stddef.h>" >> $@
	@echo "static const uint32_t vert_spv[] = {" >> $@
	@od -v -An -tx4 -w4 /tmp/vert.spv | sed 's/ /0x/g; s/\t/ /g; s/$$/,/' >> $@
	@echo "};" >> $@
	@echo "static const uint32_t frag_spv[] = {" >> $@
	@od -v -An -tx4 -w4 /tmp/frag.spv | sed 's/ /0x/g; s/\t/ /g; s/$$/,/' >> $@
	@echo "};" >> $@
	@echo "static const size_t vert_size = sizeof(vert_spv);" >> $@
	@echo "static const size_t frag_size = sizeof(frag_spv);" >> $@
	@echo "#endif" >> $@
	@rm -f /tmp/vert.spv /tmp/frag.spv


clean:
	rm -rf $(BUILD_DIR)
	rm -f src/shaders/shaderdump.h

install-toolchain:
	@echo "$(GREEN)Install slangc shader compiler locally or system-wide ?$(RESET)"
	@read -p "Choice (1=local, 2=system): " choice; \
	if [ "$$choice" = "1" ]; then \
		$(MAKE) install-toolchain-local; \
	elif [ "$$choice" = "2" ]; then \
		$(MAKE) install-toolchain-system; \
	else \
		echo "$(RED)Invalid choice$(RESET)"; \
		exit 1; \
	fi

install-toolchain-local:
	@mkdir -p $(TOOLCHAIN_DIR)
	@if [ -d $(SLANG_SRC)/.git ]; then \
		echo "$(GREEN)Updating existing slang repository...$(RESET)"; \
		cd $(SLANG_SRC) && git pull && git submodule update --init --recursive; \
	else \
		echo "$(GREEN)Cloning slang repository...$(RESET)"; \
		git clone $(SLANG_REPO) $(SLANG_SRC); \
		cd $(SLANG_SRC) && git submodule update --init --recursive; \
	fi
	@cd $(SLANG_SRC) && cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(abspath $(TOOLCHAIN_DIR)) -G Ninja 2>/dev/null || cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(abspath $(TOOLCHAIN_DIR))
	@cd $(SLANG_SRC) && (ninja -C build install 2>/dev/null || make -C build -j$$(nproc) install)
	@CUR_OWNER=$$(stat -c '%u' $(TOOLCHAIN_DIR) 2>/dev/null || stat -f '%u' $(TOOLCHAIN_DIR) 2>/dev/null); \
	if [ "$$CUR_OWNER" != "$(REAL_UID)" ]; then \
		echo "$(YELLOW)Fixing ownership of $(TOOLCHAIN_DIR)...$(RESET)"; \
		if [ $$(id -u) -eq 0 ]; then \
			chown -R $(REAL_UID):$(REAL_GID) $(TOOLCHAIN_DIR); \
		elif command -v doas >/dev/null 2>&1; then \
			doas chown -R $(REAL_UID):$(REAL_GID) $(TOOLCHAIN_DIR); \
		elif command -v sudo >/dev/null 2>&1; then \
			sudo chown -R $(REAL_UID):$(REAL_GID) $(TOOLCHAIN_DIR); \
		fi; \
	fi
	@echo "$(GREEN)Local slangc installed to $(TOOLCHAIN_DIR)/bin$(RESET)"

install-toolchain-system:
	@mkdir -p $(TOOLCHAIN_DIR)
	@if [ -d $(SLANG_SRC)/.git ]; then \
		echo "$(GREEN)Updating existing slang repository...$(RESET)"; \
		cd $(SLANG_SRC) && git pull && git submodule update --init --recursive; \
	else \
		echo "$(GREEN)Cloning slang repository...$(RESET)"; \
		git clone $(SLANG_REPO) $(SLANG_SRC); \
		cd $(SLANG_SRC) && git submodule update --init --recursive; \
	fi
	@cd $(SLANG_SRC) && cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja 2>/dev/null || cmake -B build -DCMAKE_BUILD_TYPE=Release
	@if [ $$(id -u) -eq 0 ]; then \
		echo "Running as root, installing directly..."; \
		cd $(SLANG_SRC) && (ninja -C build install 2>/dev/null || make -C build -j$$(nproc) install); \
	elif command -v doas >/dev/null 2>&1; then \
		echo "Using doas..."; \
		cd $(SLANG_SRC) && doas sh -c "ninja -C build install 2>/dev/null || make -C build -j$$(nproc) install"; \
	elif command -v sudo >/dev/null 2>&1; then \
		echo "Using sudo..."; \
		cd $(SLANG_SRC) && sudo sh -c "ninja -C build install 2>/dev/null || make -C build -j$$(nproc) install"; \
	elif command -v su >/dev/null 2>&1; then \
		echo "Using su (will prompt for root password)..."; \
		cd $(SLANG_SRC) && su -c "ninja -C build install 2>/dev/null || make -C build -j$$(nproc) install"; \
	else \
		echo "$(RED)Error: No way to gain root privileges$(RESET)"; \
		exit 1; \
	fi
	@echo "$(GREEN)slangc installed$(RESET)"

clean-toolchain:
	rm -rf $(TOOLCHAIN_DIR)

.PHONY: all compile run release debug clean install-toolchain clean-toolchain install-toolchain-local install-toolchain-system
