DEBUGGER  := lldb
BUILD_DIR ?= build
SRCS      := src/main.c
GLSLC     := glslc

UNAME_S := $(shell uname -s 2>/dev/null)

ifeq ($(PLATFORM),)
  ifneq (,$(findstring MINGW,$(UNAME_S)))
    PLATFORM := windows
  else ifneq (,$(findstring MSYS,$(UNAME_S)))
    PLATFORM := windows
  else
    PLATFORM := linux
  endif
endif

ifeq ($(PLATFORM),linux)
    CC       := cc
    TARGET   := $(BUILD_DIR)/mcp
    LDFLAGS_BASE  := -lglfw -lm
    NATIVE_TUNING := -march=native -mtune=native
	SANITIZERS    := -fsanitize=address,undefined -fno-omit-frame-pointer
    SANITIZERS_LD := -fsanitize=address,undefined
    ASAN_OPTIONS  := detect_leaks=1:halt_on_error=0
    UBSAN_OPTIONS := print_stacktrace=1:halt_on_error=0
    LSAN_OPTIONS  := suppressions=$(CURDIR)/lsan.supp:print_suppressions=0
else ifeq ($(PLATFORM),windows)
    CC       := clang
    TARGET   := $(BUILD_DIR)/mcp.exe
    LDFLAGS_BASE  := -lglfw3 -lgdi32 -luser32 -lshell32
    NATIVE_TUNING :=
    SANITIZERS    :=
    SANITIZERS_LD :=
else ifeq ($(PLATFORM),mingw)
    CC       := x86_64-w64-mingw32-gcc
    TARGET   := $(BUILD_DIR)/mcp.exe
    PLATFORM_INCLUDES := -I./lib/win64/glfw/include
    LDFLAGS_BASE  := -L./lib/win64/glfw -lglfw3 -lgdi32 -luser32 -lshell32
    NATIVE_TUNING :=
    SANITIZERS    :=
    SANITIZERS_LD :=
else
    $(error Unknown PLATFORM=$(PLATFORM). Use linux, windows or mingw)
endif

CFLAGS_COMMON := -pipe -Wall -Werror -I./src -I./lib -I./lib/vulkan-headers $(PLATFORM_INCLUDES)

CFLAGS_RELEASE  := $(CFLAGS_COMMON) -O2 $(NATIVE_TUNING) -flto -DNDEBUG
LDFLAGS_RELEASE := $(LDFLAGS_BASE)

CFLAGS_DEBUG  := $(CFLAGS_COMMON) -O0 -g3 -DDEBUG $(SANITIZERS)
LDFLAGS_DEBUG := $(LDFLAGS_BASE) $(SANITIZERS_LD)

CFLAGS := $(CFLAGS_RELEASE)
LDFLAGS := $(LDFLAGS_RELEASE)

YELLOW := \033[33m
GREEN  := \033[32m
RED    := \033[31m
RESET  := \033[0m

all: clean compile

windows:
	@$(MAKE) PLATFORM=mingw compile

run: clean compile
	@echo "$(GREEN)Running $(TARGET):$(RESET)"
	@./$(TARGET)

release: CFLAGS := $(CFLAGS_RELEASE)
release: LDFLAGS := $(LDFLAGS_RELEASE)
release: clean compile

debug: CFLAGS := $(CFLAGS_DEBUG)
debug: LDFLAGS := $(LDFLAGS_DEBUG)
debug: clean compile
	@echo "$(GREEN)Running in DEBUG mode with Sanitizers:$(RESET)"
	@ASAN_OPTIONS="$(ASAN_OPTIONS)" UBSAN_OPTIONS="$(UBSAN_OPTIONS)" LSAN_OPTIONS="$(LSAN_OPTIONS)" ./$(TARGET)

compile: $(TARGET)

$(TARGET): $(SRCS) src/shaders/shaderdump.h
	@mkdir -p $(BUILD_DIR)
	@echo "$(GREEN)[$(PLATFORM)] Compiling $(TARGET):$(RESET)"
	$(CC) $(CFLAGS) -o $@ $(SRCS) $(LDFLAGS)

src/shaders/shaderdump.h: src/shaders/shader.vert src/shaders/shader.frag src/shaders/shader.comp
	@mkdir -p $(BUILD_DIR)
	@if ! command -v $(GLSLC) > /dev/null 2>&1; then \
		echo "$(RED)Error: glslc not found. Install the Vulkan SDK (LunarG) or your distro's vulkan-tools/shaderc package$(RESET)"; \
		exit 1; \
	fi
	@echo "$(GREEN)Compiling shaders with $(GLSLC)...$(RESET)"
	@$(GLSLC) -fshader-stage=vertex   src/shaders/shader.vert -o $(BUILD_DIR)/vert.spv
	@$(GLSLC) -fshader-stage=fragment src/shaders/shader.frag -o $(BUILD_DIR)/frag.spv
	@$(GLSLC) -fshader-stage=compute  src/shaders/shader.comp -o $(BUILD_DIR)/comp.spv
	@echo "// Auto-generated by Make shader hex-dump" > $@
	@echo "" >> $@
	@echo "#ifndef SHADERDUMP_H" >> $@
	@echo "#define SHADERDUMP_H" >> $@
	@echo "#include <stdint.h>" >> $@
	@echo "#include <stddef.h>" >> $@
	@echo "static const uint32_t vert_spv[] = {" >> $@
	@od -v -An -tx4 -w4 $(BUILD_DIR)/vert.spv | sed 's/ /0x/g; s/\t/ /g; s/$$/,/' >> $@
	@echo "};" >> $@
	@echo "static const uint32_t frag_spv[] = {" >> $@
	@od -v -An -tx4 -w4 $(BUILD_DIR)/frag.spv | sed 's/ /0x/g; s/\t/ /g; s/$$/,/' >> $@
	@echo "};" >> $@
	@echo "static const uint32_t comp_spv[] = {" >> $@
	@od -v -An -tx4 -w4 $(BUILD_DIR)/comp.spv | sed 's/ /0x/g; s/\t/ /g; s/$$/,/' >> $@
	@echo "};" >> $@
	@echo "static const size_t vert_size = sizeof(vert_spv);" >> $@
	@echo "static const size_t frag_size = sizeof(frag_spv);" >> $@
	@echo "static const size_t comp_size = sizeof(comp_spv);" >> $@
	@echo "#endif" >> $@
	@rm -f $(BUILD_DIR)/vert.spv $(BUILD_DIR)/frag.spv $(BUILD_DIR)/comp.spv

clean:
	rm -rf $(BUILD_DIR)
	rm -f src/shaders/shaderdump.h

.PHONY: all compile run release debug clean windows
