CC        := clang
DEBUGGER  := lldb
BUILD_DIR ?= build
TARGET    := $(BUILD_DIR)/ucp
SRCS      := src/main.c

GLSLC := glslc

CFLAGS_COMMON := -pipe -Wall -Werror -I./src -I./lib
LDFLAGS_BASE  := -lglfw -lvulkan -lm

CFLAGS_RELEASE := $(CFLAGS_COMMON) -O2 -march=native -mtune=native -flto -DNDEBUG
LDFLAGS_RELEASE := $(LDFLAGS_BASE)

CFLAGS_DEBUG := $(CFLAGS_COMMON) -O0 -g3 -DDEBUG -fsanitize=address,undefined -fno-omit-frame-pointer
LDFLAGS_DEBUG := $(LDFLAGS_BASE) -fsanitize=address,undefined

CFLAGS := $(CFLAGS_RELEASE)
LDFLAGS := $(LDFLAGS_RELEASE)

YELLOW := \033[33m
GREEN  := \033[32m
RED    := \033[31m
RESET  := \033[0m

all: clean compile

run: clean compile
	@echo "$(GREEN)Running $(TARGET):$(RESET)"
	@./$(TARGET)

release: CFLAGS := $(CFLAGS_RELEASE)
release: LDFLAGS := $(LDFLAGS_RELEASE)
release: clean compile

debug: CFLAGS := $(CFLAGS_DEBUG)
debug: LDFLAGS := $(LDFLAGS_DEBUG)
debug: clean compile
	@echo "$(GREEN)Running in DEBUG mode with Sanitizers:$(RESET)"
	@./$(TARGET)

compile: $(TARGET)

$(TARGET): $(SRCS) src/shaders/shaderdump.h
	@mkdir -p $(BUILD_DIR)
	@echo "$(GREEN)Compiling $(TARGET):$(RESET)"
	$(CC) $(CFLAGS) -o $@ $(SRCS) $(LDFLAGS)

src/shaders/shaderdump.h: src/shaders/shader.vert src/shaders/shader.frag
	@mkdir -p $(BUILD_DIR)
	@if ! command -v $(GLSLC) > /dev/null 2>&1; then \
		echo "$(RED)Error: glslc not found. Install the Vulkan SDK (LunarG) or your distro's vulkan-tools/shaderc package$(RESET)"; \
		exit 1; \
	fi
	@echo "$(GREEN)Compiling shaders with $(GLSLC)...$(RESET)"
	@$(GLSLC) -fshader-stage=vertex   src/shaders/shader.vert -o /tmp/vert.spv
	@$(GLSLC) -fshader-stage=fragment src/shaders/shader.frag -o /tmp/frag.spv
	@echo "// Auto-generated by Make shader hex-dump" > $@
	@echo "" >> $@
	@echo "#ifndef SHADERDUMP_H" >> $@
	@echo "#define SHADERDUMP_H" >> $@
	@echo "#include <stdint.h>" >> $@
	@echo "#include <stddef.h>" >> $@
	@echo "static const uint32_t vert_spv[] = {" >> $@
	@od -v -An -tx4 -w4 /tmp/vert.spv | sed 's/ /0x/g; s/\t/ /g; s/$$/,/' >> $@
	@echo "};" >> $@
	@echo "static const uint32_t frag_spv[] = {" >> $@
	@od -v -An -tx4 -w4 /tmp/frag.spv | sed 's/ /0x/g; s/\t/ /g; s/$$/,/' >> $@
	@echo "};" >> $@
	@echo "static const size_t vert_size = sizeof(vert_spv);" >> $@
	@echo "static const size_t frag_size = sizeof(frag_spv);" >> $@
	@echo "#endif" >> $@
	@rm -f /tmp/vert.spv /tmp/frag.spv

clean:
	rm -rf $(BUILD_DIR)
	rm -f src/shaders/shaderdump.h

.PHONY: all compile run release debug clean
